import { CheckCircle2, ExternalLink, Globe, RefreshCw } from "lucide-react";
import { merchantIssues, type MarketingProduct } from "@/features/products/marketing";

export function CatalogSeoOverview({ products, loading }: { products: MarketingProduct[]; loading: boolean }) {
  const published = products.filter(product => product.status === "ACTIVE");
  const ready = published.filter(product => merchantIssues(product).length === 0).length;
  return <section aria-label="Produtos no Google" className="rounded-xl border border-emerald-100 bg-emerald-50/50 p-5">
    <div className="flex items-start gap-3"><Globe className="mt-0.5 h-6 w-6 shrink-0 text-emerald-700" /><div><h2 className="text-base font-black text-ink">Seus produtos preparados para o Google</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Ao publicar um produto, o site cria sua página e a inclui automaticamente no mapa do site. Nome, foto, preço e descrição são atualizados quando você edita o cadastro. Isso vale para os produtos atuais e os próximos, sem precisar enviar links um por um.</p></div></div>
    <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-emerald-800"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4" />Página e dados do produto</span><span className="flex items-center gap-2"><RefreshCw className="h-4 w-4" />Sitemap e catálogo automáticos</span></div>
    {!loading && <div className="mt-4 rounded-lg border border-line bg-white p-4 text-sm leading-6"><p className="font-bold text-ink">Nesta lista: {published.length} publicados no site · {ready} aptos para o catálogo Shopping</p><p className="mt-1 text-muted">{published.length > ready ? "Há produtos com dados pendentes ou sujeitos a restrições. Abra “SEO e marketing” no produto para ver o que conferir. Corrigir o cadastro atualiza a fonte automaticamente." : "Os dados passam na verificação do site. A aprovação e a exibição nas vitrines ainda dependem do Google."}</p></div>}
    <details className="mt-4 border-t border-emerald-100 pt-2"><summary className="cursor-pointer py-3 text-sm font-bold text-ink">Configuração única no Google e como acompanhar</summary><div className="space-y-3 pb-2 text-sm leading-6 text-muted">
      <p><strong className="text-ink">Busca do Google:</strong> o site está preparado para ser encontrado. Para acompanhar a indexação, adicione e confirme a propriedade no Search Console uma vez e informe o sitemap abaixo. Depois, novos produtos entram automaticamente nesse mesmo sitemap.</p>
      <div className="flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center gap-2 font-bold text-brand underline" href="https://search.google.com/search-console" target="_blank" rel="noopener noreferrer">Abrir Search Console <ExternalLink className="h-3 w-3" /></a><a className="inline-flex min-h-11 items-center gap-2 break-all font-bold text-brand underline" href="https://wimifarma.com.br/sitemap.xml" target="_blank" rel="noopener noreferrer">Ver sitemap.xml <ExternalLink className="h-3 w-3" /></a></div>
      <p><strong className="text-ink">Vitrines de produtos / Shopping:</strong> no Merchant Center, cadastre uma fonte de dados por URL com busca programada usando <code className="break-all text-xs text-ink">https://wimifarma.com.br/google-products.xml</code>. A fonte se atualiza com o catálogo; medicamentos e itens sujeitos a restrições precisam de análise separada.</p>
      <div className="flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center gap-2 font-bold text-brand underline" href="https://merchants.google.com/" target="_blank" rel="noopener noreferrer">Abrir Merchant Center <ExternalLink className="h-3 w-3" /></a><a className="inline-flex min-h-11 items-center gap-2 font-bold text-brand underline" href="/google-products.xml" target="_blank" rel="noopener noreferrer">Ver catálogo automático <ExternalLink className="h-3 w-3" /></a></div>
      <p className="text-xs">Publicar no site não confirma indexação nem aprovação pelo Google. A descoberta pode levar dias, e a posição nos resultados é definida pelo Google. Compartilhar links e fazer anúncios são opções adicionais.</p>
    </div></details>
  </section>;
}
